package org.apache.commons.graph.export;

/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import java.io.IOException;
import java.io.PrintWriter;
import java.io.Writer;
import java.util.Date;

import org.apache.commons.graph.DirectedGraph;
import org.apache.commons.graph.Edge;
import org.apache.commons.graph.Graph;
import org.apache.commons.graph.Labeled;
import org.apache.commons.graph.Vertex;
import org.apache.commons.graph.VertexPair;
import org.apache.commons.graph.WeightedEdge;

final class DefaultNamedEsportSelector<V extends Vertex, E extends Edge, G extends Graph<V, E>>
    implements NamedExportSelctor<V, E, G>
{

    private static final String GRAPH = "graph";

    private static final String DIGRAPH = "digraph";

    private static final String CONNECTOR = "--";

    private static final String DICONNECTOR = "->";

    private final G graph;

    private final Writer writer;

    private final String name;

    public DefaultNamedEsportSelector( G graph, Writer writer )
    {
        this( graph, writer, null );
    }

    public DefaultNamedEsportSelector( G graph, Writer writer, String name )
    {
        this.graph = graph;
        this.writer = writer;
        this.name = name;
    }

    public void usingDotNotation()
    {
        String graphDeclaration;
        String connector;

        if ( graph instanceof DirectedGraph )
        {
            graphDeclaration = DIGRAPH;
            connector = DICONNECTOR;
        }
        else
        {
            graphDeclaration = GRAPH;
            connector = CONNECTOR;
        }

        PrintWriter printWriter = new PrintWriter( writer );
        try
        {
            printWriter.format( "# Graph generated by Apache Commons Graph on %s%n", new Date() );
            printWriter.format( "%s %s {%n", graphDeclaration, name != null ? name : 'G' );

            for ( V vertex : graph.getVertices() )
            {
                printWriter.format( "  %s [label=\"%s\"];%n",
                                    vertex.hashCode(),
                                    ( vertex instanceof Labeled) ? ( (Labeled) vertex).getLabel() : vertex.toString() );
            }

            for ( E edge : graph.getEdges() )
            {
                VertexPair<V> vertexPair = graph.getVertices( edge );

                printWriter.format( "  %s %s %s",
                                    vertexPair.getHead().hashCode(),
                                    connector,
                                    vertexPair.getTail().hashCode() );

                boolean attributesFound = false;

                if ( edge instanceof Labeled )
                {
                    attributesFound = true;
                    printWriter.format( " [label=\"%s\"", ( (Labeled) edge ).getLabel() );
                }
                if ( edge instanceof WeightedEdge )
                {
                    Object weight = ( (WeightedEdge<?>) edge ).getWeight();

                    if ( weight instanceof Number )
                    {
                        printWriter.format( " " );

                        if ( !attributesFound )
                        {
                            printWriter.format( "[" );
                            attributesFound = true;
                        }

                        printWriter.format( "weight=%f", ( (Number) weight ).doubleValue() );
                    }
                }

                if ( attributesFound )
                {
                    printWriter.format( "]" );
                }

                printWriter.format( "%n" );
            }

            printWriter.write( '}' );
        }
        finally
        {
            try
            {
                writer.close();
            }
            catch ( IOException e )
            {
                // swallow it
            }
        }
    }

    public ExportSelctor<V, E, G> withName( String name )
    {
        return new DefaultNamedEsportSelector<V, E, G>( graph, writer, name );
    }

}
